### ISSUE TITLE
Ready for prime time, or unmaintained?

### ISSUE THREAD

**Issue by ShalokShalom** [joshday/SQLiteGraph.jl#10]
Considering how this implementation is mentioned at the [original simple-graph repo](https://github.com/dpapathanasiou/simple-graph#importable-library-free), is it correct that SQLiteGraph kinda depends on it?

Is the slow or halted development of this repo related to that?
Or do we simply have not the resources at the time, to update it?

**Comment by joshday** [comment]
>  is it correct that SQLiteGraph kinda depends on it?

No.  I simply borrowed/stole some ideas from there and wanted to give credit.

> Is the slow or halted development of this repo related to that?

I implemented everything I had a use case for and then stopped.

---

> Ready for prime time, or unmaintained?

I'd say neither but closer to unmaintained (I would certainly review any PRs however).  It follows semantic versioning (https://semver.org/#spec-item-4), so as a 0.X release nothing is stable.  I may have a reason to pick this up again soon, but that reason also may not happen.
